baseURL = 'https://aalai.alexgarth.co.uk/'
languageCode = 'en-us'
title = 'AALAI'

theme = 'lugo'

[params]
  taglist = false
  nextprev = false
  datesinlist = false
  authorsinlist = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
